---
- name: Gather OS specific variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution_release }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - default.yml
  tags:
    - vars

- name: Check installed rclone version
  import_tasks: versioncheck.yml

- name: Install from binary
  include_tasks: install-bin.yml
  when:
    - ansible_os_family != "Archlinux"
    - >-
      (((not ansible_local.rclone.installed|d())|bool) or
      (ansible_local.rclone.installed_version|d("0.0.0")) != rclone_version)

- name: Install from package
  include_tasks: install-package.yml
  when:
    - ansible_os_family == "Archlinux"

- name: Merge configs
  ansible.builtin.set_fact:
    rclone_configs: '{{ rclone_configs + rclone_configs_extra }}'
  when: rclone_configs is defined and rclone_configs_extra is defined

- name: Install configs
  block:
    - name: Create config directory
      ansible.builtin.file:
        path: '{{ rclone_config_location | dirname }}'
        state: directory
        mode: '0700'

    - name: Set up rclone config
      ansible.builtin.template:
        src: rclone.conf.j2
        dest: '{{ rclone_config_location }}'
        mode: 0600
  become: true
  when: rclone_configs is defined

- name: Update Ansible facts if they were modified
  action: ansible.builtin.setup
